mod agent;
mod error;
mod fsops;
mod git;
mod github;
mod hooks;
mod instructions;
mod secrets;
mod state;

use state::AppState;

#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub fn run() {
    tauri::Builder::default()
        .plugin(tauri_plugin_opener::init())
        .plugin(tauri_plugin_http::init())
        .plugin(tauri_plugin_notification::init())
        .plugin(tauri_plugin_store::Builder::new().build())
        .plugin(tauri_plugin_dialog::init())
        .plugin(tauri_plugin_process::init())
        .setup(|app| {
            // Desktop-only auto-updater (GitHub Releases). No-op on mobile.
            #[cfg(desktop)]
            app.handle()
                .plugin(tauri_plugin_updater::Builder::new().build())?;
            Ok(())
        })
        .manage(AppState::default())
        .invoke_handler(tauri::generate_handler![
            git::repo::check_git_installed,
            git::repo::validate_repo,
            git::repo::clone_repo,
            git::repo::create_repo,
            git::repo::git_repo_owners,
            git::status::git_status,
            git::branches::git_branches,
            git::branches::git_checkout_branch,
            git::branches::git_create_branch,
            git::branches::git_rename_branch,
            git::branches::git_delete_branch,
            git::branches::git_default_branch,
            git::branches::git_branch_divergence,
            git::branches::git_branch_merge_states,
            git::branches::git_set_branch_archived,
            git::branches::git_update_branch_from,
            git::diff::git_diff_file,
            git::diff::git_staged_diff,
            git::diff::git_apply_patch,
            git::diff::git_apply_partial,
            git::diff::git_file_base64,
            git::stage::git_stage,
            git::stage::git_unstage,
            git::commit::git_commit,
            git::commit::git_commit_authors,
            git::commit::git_user_identity,
            git::commit::git_global_identity,
            git::commit::git_set_global_identity,
            git::commit::git_undo_commit,
            git::commit::git_recent_commits,
            git::history::git_log,
            git::history::git_file_log,
            git::history::git_blame,
            git::history::git_commit_details,
            git::history::git_commit_files,
            git::history::git_commit_file_diff,
            git::history::git_commit_diff,
            git::ops::git_discard,
            git::ops::git_reset,
            git::ops::git_checkout_commit,
            git::ops::git_revert,
            git::ops::git_cherry_pick,
            git::ops::git_cherry_pick_onto,
            git::ops::git_rewrite_commits,
            git::ops::git_tag,
            git::ops::git_push_tag,
            git::ops::git_delete_tag,
            git::ops::git_discard_all,
            git::ops::git_discard_paths,
            git::ops::git_stash_all,
            git::ops::git_stash_paths,
            git::ops::git_untrack,
            git::ops::git_stash_pop,
            git::ops::git_stash_count,
            git::ops::git_stash_list,
            git::ops::git_stash_files,
            git::ops::git_stash_file_diff,
            git::ops::git_stash_apply,
            git::ops::git_stash_drop,
            git::ops::git_merge,
            git::ops::git_rebase,
            git::ops::git_op_state,
            git::ops::git_op_abort,
            git::ops::git_op_continue,
            git::ops::git_merge_local_pr,
            git::stats::git_repo_stats,
            git::stats::git_branch_stats,
            git::compare::git_compare_branches,
            git::compare::git_branch_diff_files,
            git::compare::git_branch_file_diff,
            git::compare::git_branch_diff,
            github::pr::gh_status,
            github::pr::gh_accounts,
            github::pr::gh_switch_account,
            github::pr::gh_list_repos,
            github::pr::gh_pr_create,
            github::pr::gh_repo_url,
            github::pr::gh_publish_repo,
            github::pr::gh_prs_for_branch,
            github::pr::gh_pr_list,
            github::pr::gh_pr_poll,
            github::pr::gh_pr_view,
            github::pr::gh_pr_diff,
            github::pr::gh_pr_review,
            github::pr::gh_pr_comment,
            github::pr::gh_pr_edit_comment,
            github::pr::gh_pr_delete_comment,
            github::pr::gh_pr_minimize_comment,
            github::pr::gh_pr_unminimize_comment,
            github::pr::gh_pr_merge,
            github::pr::gh_pr_close,
            github::pr::gh_pr_reopen,
            github::pr::gh_pr_checkout,
            github::pr::gh_repo_fork,
            github::pr::gh_pr_ready,
            github::pr::gh_pr_edit,
            github::pr::gh_repo_labels,
            github::pr::gh_branch_protections,
            github::pr::gh_pr_edit_labels,
            github::actions::gh_run_list,
            github::actions::gh_run_view,
            github::actions::gh_run_rerun,
            github::actions::gh_run_cancel,
            github::actions::gh_run_failed_logs,
            github::actions::gh_job_logs,
            github::actions::gh_workflow_list,
            github::actions::gh_workflow_run,
            fsops::append_to_gitignore,
            fsops::read_text_file,
            fsops::delete_repo_folder,
            fsops::reveal_in_explorer,
            fsops::open_with_default,
            fsops::open_in_terminal,
            fsops::open_with_program,
            fsops::detect_editors,
            fsops::detect_terminals,
            git::remote::git_fetch,
            git::remote::git_pull,
            git::remote::git_push,
            git::remote::git_remotes,
            git::remote::git_remote_url,
            git::remote::git_remote_set_url,
            git::submodule::git_submodules,
            git::submodule::git_submodule_update,
            secrets::set_secret,
            secrets::get_secret,
            secrets::delete_secret,
            secrets::secret_exists,
            instructions::read_repo_instructions,
            instructions::read_repo_ai_ignore,
            instructions::read_repo_branch_rules,
            instructions::write_repo_branch_rules,
            instructions::read_repo_syntax,
            instructions::write_repo_syntax,
            hooks::git_hooks_list,
            hooks::git_hook_read,
            hooks::git_hook_write,
            hooks::git_hook_set_enabled,
            hooks::git_hook_delete,
            hooks::git_run_hook_manager,
            agent::agent_detect,
            agent::agent_review,
            agent::agent_review_cancel,
        ])
        .run(tauri::generate_context!())
        .expect("error while running tauri application");
}
